version: '2.1'
services: 
  elastic-xpack:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elastic-xpack
    hostname: elastic-xpack
    ports:
      - 9200:9200
    environment:
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
      xpack.security.enabled: "false"
    networks:
      - microservicenet 

networks:
  microservicenet:
   driver: bridge
